import time
from pathlib import Path

import faiss
import numpy as np
import pandas as pd
import yaml
from llama_index.core import Document, StorageContext, VectorStoreIndex
from llama_index.core.node_parser import (
    SemanticSplitterNodeParser,
    SentenceWindowNodeParser,
    TokenTextSplitter,
)
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.vector_stores.faiss import FaissVectorStore
from pypdf import PdfReader
from sklearn.metrics.pairwise import cosine_similarity

ROOT = Path(__file__).resolve().parent.parent
CORPUS = ROOT / "reports" / "hw03" / "corpus"
QUESTIONS = ROOT / "reports" / "hw03" / "questions.yaml"
RAW = ROOT / "reports" / "hw03" / "raw"
METRICS = ROOT / "reports" / "hw03" / "METRICS.md"
MODEL = "sentence-transformers/all-MiniLM-L6-v2"
K = 5
TECHNIQUES = ["token-based chunking", "semantic chunking", "sentence-window chunking"]


def load_docs():
    docs = []
    for path in sorted(CORPUS.glob("*.pdf")): # iterate over all pdf files in the corpus with sorted order
        pages = []
        for page in PdfReader(str(path)).pages:
            text = (page.extract_text() or "").encode("utf-8", "surrogatepass").decode("utf-8", "ignore")
            pages.append(text)
        docs.append(Document(text="\n".join(pages), metadata={"file_name": path.name}))
    return docs


def load_questions():
    items = yaml.safe_load(QUESTIONS.read_text(encoding="utf-8"))
    return [
        {
            "q_num": i,
            "question": item[f"question{i}"],
            "expected_source": item["expected_source"],
        }
        for i, item in enumerate(items, 1)
    ]


# Chunking -> Nodes
def make_nodes(docs, technique, embed_model): # create nodes from the documents
    parsers = {
        "token-based chunking": TokenTextSplitter(chunk_size=512, chunk_overlap=50),
        "semantic chunking": SemanticSplitterNodeParser(embed_model=embed_model, buffer_size=1),
        "sentence-window chunking": SentenceWindowNodeParser.from_defaults(window_size=3),
    }
    return parsers[technique].get_nodes_from_documents(docs)


# Indexing 
def make_index(nodes, embed_model): 
    dim = len(embed_model.get_text_embedding("dummy text")) # get the dimension of the embedding vector generated by the embedding model， we are using model all-MiniLM-L6-v2 from huggingface
    storage = StorageContext.from_defaults(
        vector_store=FaissVectorStore(faiss_index=faiss.IndexFlatIP(dim)) 
    ) # custom storage context using faiss for similarity search
    return VectorStoreIndex(nodes, storage_context=storage, embed_model=embed_model) # nodes are transformed into vectors and stored in the vector store, returns a vector store index

# Retrieval
def retrieve(index, embed_model, query, k):
    qvec = np.asarray(embed_model.get_query_embedding(query), dtype=float) # generate the embedding vector for the query
    t0 = time.perf_counter() # start time
    hits = index.as_retriever(similarity_top_k=k).retrieve(query) # retrieve the top k most similar nodes to the query
    latency_ms = (time.perf_counter() - t0) * 1000 # calculate the latency in milliseconds
    rows = []  
    doc_vecs = [] 
    for rank, hit in enumerate(hits, 1): # enumerate the hits and get the rank, hit, and text
        text = (hit.node.metadata or {}).get("window") or hit.node.get_content() # sentence-window chunking or token-based chunking, only for sentence-window has metadata key "window"
        dvec = np.asarray(embed_model.get_text_embedding(text), dtype=float) # generate the embedding vector for the text
        doc_vecs.append(dvec)
        rows.append(
            {
                "rank": rank,
                "store_score": None if hit.score is None else float(hit.score),
                "cosine_sim": float(cosine_similarity([qvec], [dvec])[0, 0]),
                "chunk_len": len(text),
                "preview": " ".join(text.split())[:160],
                "source": (hit.node.metadata or {}).get("file_name", ""),
            }
        )
    
    return {
        "query_dim": int(qvec.size),
        "query_first8": [round(float(x), 4) for x in qvec[:8]],
        "latency_ms": round(latency_ms, 2),
        "hits": rows,
        "query_shape": list(qvec.shape),
        "docs_shape": list(np.vstack(doc_vecs).shape)
    }


def write_csv(results):
    rows = []
    for rec in results:
        for hit in rec["hits"]:
            rows.append(
                {
                    "technique": rec["technique"],
                    "q_num": rec["q_num"],
                    "rank": hit["rank"],
                    "store_score": hit["store_score"],
                    "cosine_sim": hit["cosine_sim"],
                    "chunk_len": hit["chunk_len"],
                    "preview": hit["preview"],
                    "latency_ms": rec["latency_ms"],
                    "source": hit["source"],
                    "expected_source": rec["expected_source"],
                }
            )
    pd.DataFrame(rows).to_csv(RAW / "summary.csv", index=False)


def write_metrics(stats):
    df = pd.read_csv(RAW / "summary.csv")
    stats_by_t = {row["technique"]: row for row in stats}
    rows = []
    for (technique, q_num), g in df.groupby(["technique", "q_num"], sort=False):
        rows.append(
            {
                "technique": technique,
                "top1_cosine": float(g.loc[g["rank"] == 1, "cosine_sim"].iloc[0]),
                "mean_at_k_cosine": float(g["cosine_sim"].mean()),
                "recall_at_k": int(g["expected_source"].iloc[0] in set(g["source"])),
                "latency_ms": float(g["latency_ms"].iloc[0]),
                "n_chunks": stats_by_t[technique]["n_chunks"],
                "avg_chunk_len": stats_by_t[technique]["avg_chunk_len"],
            }
        )
    metrics = (
        pd.DataFrame(rows)
        .groupby("technique", sort=False)
        .agg(
            chunks=("n_chunks", "first"),
            avg_chunk_len=("avg_chunk_len", "first"),
            top1_cosine=("top1_cosine", "mean"),
            mean_at_k_cosine=("mean_at_k_cosine", "mean"),
            recall_at_k=("recall_at_k", "mean"),
            mean_latency_ms=("latency_ms", "mean"),
        )
        .reindex(TECHNIQUES)
        .reset_index()
    )
    lines = [
        "# Retrieval comparison",
        "",
        "k = 5. Cosine and recall are means over the five questions. Recomputed from raw/summary.csv.",
        "",
        "| Technique | Chunks | Avg chunk length | Top-1 cosine | Mean cosine @ k | Recall@k | Mean retrieval latency (ms) |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in metrics.itertuples(index=False):
        lines.append(
            f"| {row.technique} | {int(row.chunks)} | {row.avg_chunk_len:.1f} | "
            f"{row.top1_cosine:.3f} | {row.mean_at_k_cosine:.3f} | {row.recall_at_k:.1f} | "
            f"{row.mean_latency_ms:.1f} |"
        )
    lines.append("")
    METRICS.write_text("\n".join(lines))
    print("\n=== metrics ===")
    print(metrics.to_string(index=False))


def run():
    RAW.mkdir(parents=True, exist_ok=True)
    embed_model = HuggingFaceEmbedding(model_name=MODEL, embed_batch_size=32)
    docs = load_docs()
    questions = load_questions()
    stats = []
    results = []
    for technique in TECHNIQUES:
        print(f"\nchunking {technique}")
        nodes = make_nodes(docs, technique, embed_model)
        lengths = [len((n.metadata or {}).get("window") or n.get_content()) for n in nodes]
        stats.append(
            {
                "technique": technique,
                "n_chunks": len(nodes),
                "avg_chunk_len": round(float(np.mean(lengths)), 1),
            }
        )
        print("chunks", stats[-1]["n_chunks"], "avg_len", stats[-1]["avg_chunk_len"])
        index = make_index(nodes, embed_model)
        for q in questions:
            rec = {
                "technique": technique,
                "q_num": q["q_num"],
                "question": q["question"],
                "expected_source": q["expected_source"],
                **retrieve(index, embed_model, q["question"], K),
            }
            results.append(rec)
            print(f"\n=== {technique} | q{q['q_num']} ===")
            print("query dim", rec["query_dim"], "first8", rec["query_first8"])
            print("query_shape", rec["query_shape"], "docs_shape", rec["docs_shape"])
            print("latency_ms", rec["latency_ms"])
            print(
                pd.DataFrame(rec["hits"])[
                    ["rank", "store_score", "cosine_sim", "chunk_len", "preview"]
                ].to_string(index=False)
            )
    write_csv(results)
    write_metrics(stats)


if __name__ == "__main__":
    run()
